PUT http://localhost:3001/api/books/629694af05d4231c6513143e
Content-Type: application/json

{
  "title": "12",
  "author": "31",
  "pages": 123,
  "isRead": true,
  "id": "629694af05d4231c6513143e"
}